### ISSUE TITLE
jenaTest.TermType_Test fails

### ISSUE THREAD

**Issue by mgskjaeveland** [R2RML-api/R2RML-api#5]
The failing test is from getting columns from a template. The template is
`rr:template "{\"FirstName\"} {\"LastName\"}"; rr:termType rr:Literal;` 
and the test fails when getting the first column with
`TermType_Test.test:103 expected:<["FirstName]"> but was:<[\"FirstName\]">`

The owlapi or the sesame api do not fail on the same test. Seems to be a issue of treating escaping, but not sure which way is correct?

**Comment by ghxiao** [comment]
It seems that the behavior of treating  escaping in jena library changed from v2 to v3. I will have a closer look.

**Comment by ghxiao** [comment]
The reason is that the method toString() is not reliable. 
Now there is a getLexicalForm() method in the LibConfiguration interface.
Actually similar issue for IRI representation already happened when upgrading owlapi v3 to v4.
